### PR TITLE
More tests more problems.

### PR DESCRIPTION
**Pull request by LarryBattle**
Added more test cases and switched to using a regular expression instead of a for loop.

### CODE REVIEW

**Comment by dustinhayes** [comment]
This is really good. I'm curious what the performance implications are of using regexp instead of a simple loop.

**Comment by bevacqua** [comment]
Probably abysmal. I'll put together a jsperf test

**Comment by bevacqua** [comment]
So yeah, abysmal. Closing.

http://jsperf.com/fuzzysearch-regex

**Comment by dustinhayes** [comment]
Haha holy cow!

**Pull request closed without merging**
